[build]
command = "npm run setup:client && npm run build:client"
publish = "client/dist"
functions = "netlify/functions"
edge_functions = "netlify/edge-functions"

[[edge_functions]]
function = "bridge"
path = "/bridge*"

[[edge_functions]]
function = "bridge"
path = "/register-device"

[[edge_functions]]
function = "bridge"
path = "/healthz"
